In [3]:
alist = [i for i in range(10)]
alist[:4], alist[4:]

([0, 1, 2, 3], [4, 5, 6, 7, 8, 9])

In [1]:
# 2次元行列を特定の列でソートする
import numpy as np
a = np.array([[9, 8, 5], [2, 3, 1], [0, 4, 7]])
print(a)                       # 行列の表示
print(a[:, 1])                 # 1列目を取り出す
print(np.argsort(a[:, 1]))     # ソートしたときのindex
print(a[np.argsort(a[:, 1])])  # ソート完了！

[[9 8 5]
 [2 3 1]
 [0 4 7]]
[8 3 4]
[1 2 0]
[[2 3 1]
 [0 4 7]
 [9 8 5]]


In [2]:
import numpy as np
np.array([0, 1])

array([0, 1])