In [41]:
import numpy as np
a = np.array([1,2,3,4,5])
print(a)
print(type(a))
print(np.flip(a))

[1 2 3 4 5]
<class 'numpy.ndarray'>
[5 4 3 2 1]


In [31]:
print(np.zeros(5))
print(np.zeros_like(a))
print(np.ones(5))
print(np.ones_like(a))

[0. 0. 0. 0. 0.]
[0 0 0 0 0]
[1. 1. 1. 1. 1.]
[1 1 1 1 1]
1


In [90]:
e = np.eye(3)
print(e)
print(e.ndim)
print(e.size)
print(e.shape)
print(e.flatten())

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
2
9
(3, 3)
[1. 0. 0. 0. 1. 0. 0. 0. 1.]


In [20]:
print(np.arange(1, 5, 0.5))
print(np.linspace(1, 5, 9))

[1.  1.5 2.  2.5 3.  3.5 4.  4.5]
[1.  1.5 2.  2.5 3.  3.5 4.  4.5 5. ]


In [101]:
alist = np.array([i for i in range(1, 10)])
matlix = alist.reshape(3, 3)
print(alist)
print(matlix)
print(matlix.transpose())
alist2 = np.append(alist, 10)
print(alist2)
alist2 = np.append(0, alist2)
print(alist2)
print(matlix.argmax())
print(matlix.argmin())
print(matlix.max())
print(matlix.min())


[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]
[ 1  2  3  4  5  6  7  8  9 10]
[ 0  1  2  3  4  5  6  7  8  9 10]
8
0
9
1


In [82]:
l = np.array([5, 2, 4, 1, 3])
print(np.sort(l))
print(np.argsort(l))

[1 2 3 4 5]
[3 1 4 2 0]


In [70]:
a = np.arange(6).reshape(2, 3)
print(a)
print(a.sum())

[[0 1 2]
 [3 4 5]]
15
[[ 0  1  4]
 [ 9 16 25]]
[[ 5 14]
 [14 50]]


In [73]:
a = np.arange(6)
print(a + a)
print(np.multiply(a, a))
print(np.dot(a, a))

[ 0  2  4  6  8 10]
[ 0  1  4  9 16 25]
55


In [29]:
print(np.random.rand(3))
print(np.random.rand(2, 2))
print(np.random.randint(1, 10))
print(np.random.randint(1, 10, (2, 2)))

[0.70199516 0.59967253 0.89692365]
[[0.11673914 0.50157715]
 [0.15948128 0.15416074]]
2
[[3 6]
 [6 4]]


In [5]:
# 等比数列
import numpy as np
print(np.geomspace(1, 1000, 4))

[   1.   10.  100. 1000.]
